on:
  push:
    branches:
      - date-test
jobs:
  date-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dynamically set MY_DATE environment variable
        run: echo "MY_DATE=2020-10-07T12:00:00+01:00" >> $GITHUB_ENV
      - name: Test MY_DATE variable
        run: echo ${{ env.MY_DATE }}