on:
  push:
    branches:
      - master
  workflow_dispatch:
name: Dynamic matrix parameters demo
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ${{ env.BUILD_VARIANT }} build matrix variants
        id: setup-matrix-combinations
        run: |
          MATRIX_PARAMS_COMBINATIONS='
              {"foo": "foo-1", "bar": "bar-1"},
              {"foo": "foo-1", "bar": "bar-2"},
              {"foo": "foo-2", "bar": "bar-1"},
          '
          echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      matrix-combinations: ${{ setup-matrix.setup-matrix-combinations.outputs.matrix-combinations }}
  build:
    runs-on: ubuntu-latest
    needs: set-up-matrix
    strategy:
      matrix: ${{ fromJson(needs.set-up.outputs.build-variants) }}
    steps:
      - run: |
          echo foo=${{ matrix.foo }}
          echo bar=${{ matrix.bar }}